---
abstract: 'Nureg automation reloaded'
author:
  - 'Wolfgang Kinkeldei <wolfgang@kinkeldei.de>'
build_requires:
  Carp::Heavy: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300016, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: NUREG-Automation
requires:
  Cwd: 0
  Data::Dumper: 0
  Exporter: 0
  File::ShareDir: 0
  FindBin: 0
  Getopt::Std: 0
  IPC::Open3: 0
  JSON: 0
  base: 0
  strict: 0
  warnings: 0
version: 0.03
